// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsmglqmgbqmgprcllomd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzbWdscW1nYnFtZ3ByY2xsb21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzMzIwNjYsImV4cCI6MjA1MzkwODA2Nn0.UKZs2b2zT4azyNnhOcpYyXNANJEkGsUecX9NAZb2QWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);